version: "3"
services:
  cache:
    image: redis:alpine
    restart: unless-stopped
    command: "redis-server"
    ports:
      - "6379:6379"
    volumes:
      - ~/.tg_search_bot/redis/data:/data

  tg_search_bot:
    build: .
    restart: always
    working_dir: /app
    environment:
      - TZ=Asia/Shanghai
    network_mode: "host"
    volumes:
      - .:/app
      - ~/.tg_search_bot:/root/.tg_search_bot
    depends_on:
      - cache
